config/routes.rb
PetsAlliance::Application.routes.draw do

  scope "forums/:url" do
    resources :topics
  end
  
  scope "forums/:url/topics/:topic_id" do
    resources :posts
  end
    
  resources :pets
  resources :users
  resources :quests
    
  resources :sessions,      :only => [:new, :create, :destroy]
  
  match '/worldmap', :to => 'locations#index'
  match '/explore', :to => 'locations#explore'
  match '/worldmap/setlocation', :to => 'pets#set_current_location'
  
  resources :friendships
  match 'alliance/req', :to => 'friendships#req'
  match 'alliance/accept/:id', :to => 'friendships#accept'
  match 'alliance/reject/:id', :to => 'friendships#reject'
  
  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/leaderboard', :to => 'pages#leaderboard'
  match '/alliance', :to => 'pages#alliance'
  
  match '/forums', :to => 'pages#forums'
  match '/forums/:url', :to => 'categories#show'
  
  match 'battle', :to => 'pets#battle_index'
  match 'battle/:opponent_pet_id/attack', :to => 'battles#attack'
  match 'battle/run_away', :to => 'battles#run_away'
  match 'battle/:id', :to => 'battles#_show'

  match 'pets/:id/select', :to => 'pets#set_current'
  
  match 'quests/:id/job', :to => 'quests#job'
  
  match 'shop', :to => 'items#_index'
  match 'shop/:item_type', :to => 'items#show_by_type'
  match 'shop/:pid/buy', :to => 'items#buy'
  match 'shop/:pid/sell', :to => 'items#sell'
  
  match 'inventory', :to => 'items#inventory'
  match 'inventory/:pid/equip', :to => 'items#equip'
  match 'inventory/:pid/level', :to => 'items#level_up'
  match 'unequip/:position', :to => 'items#unequip'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <top_bar class="top_bar">
    <ul>
      <li><%= link_to "Leaderboard", leaderboard_path %></li>
      <li><%= link_to "Forums", forums_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Alliance", alliance_path %></li>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Sign out", signout_path %></li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </top_bar>
  <br />
  <toolbar class="toolbar">
    <ul>
      <% if signed_in? && has_pet? && !current_pet.in_battle %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "World Map", '/worldmap' %></li>
        <li><%= link_to "Explore", '/explore' %></li>
        <li><%= link_to "Quests", quests_path %></li>
        <li><%= link_to "Shop", '/shop' %></li>
        <li><%= link_to "Inventory", '/inventory' %></li>
        <li><%= link_to "Battle", '/battle' %></li>
      <% else %>
      <% end %>
    </ul>
  </toolbar>
  
  <% if signed_in? && has_pet? && current_pet.in_battle %>

  <% end %>
</header>

app/views/layouts/_mid_header.html.erb
<div class="mid-header">
  <% if signed_in? && has_pet? && !current_pet.in_battle %>
    <div class="location_of_pet">
      <b>Your Current Location is:</b> <%= current_pet.current_location.name %>
    </div>
    <div class="pet_rechargeables">
      <div class="pet_hp_bar">
        <b>HP</b><br />
        <b><%= number_with_delimiter(current_pet.stat('curr_hp')) %></b>/<%= number_with_delimiter(current_pet.stat('max_hp')) %>
      </div>
      <div class="pet_energy_bar">
        <b>Energy</b><br />
        <b><%= number_with_delimiter(current_pet.stat('curr_energy')) %></b>/<%= number_with_delimiter(current_pet.stat('max_energy')) %>
      </div>
      <div class="pet_money">
        <b>Money</b><br />
        $<%= number_with_precision(current_pet.money.to_i, :precision => 0, :delimiter => ',') %>
      </div>
      <div class="pet_level_experience">
        <b>Experience - Level </b><%= current_pet.stat('level') %><br />
        <% next_level = PetsController::EXP_LEVELS[current_pet.stat('level')] %>
        <b><%= number_with_delimiter(current_pet.stat('experience')) %></b>/<%= number_with_delimiter(next_level) %><br />
      </div>
    </div>
    <div class="pet_stats">
      <div class="pet_stats_without_equipment">
      <div class="pet_attack_defense">
        <b>Attack</b> <%= number_with_delimiter(current_pet.stat('attack')) %> |
        <b>Defense</b> <%= number_with_delimiter(current_pet.stat('defense')) %> | 
        <b>Max HP</b> <%= number_with_delimiter(current_pet.stat('max_hp')) %> | 
        <b>Max Energy</b> <%= number_with_delimiter(current_pet.stat('max_energy')) %>
      </div>
      <div class="pet_points">
        <b>Skill Points</b> <%= number_with_delimiter(current_pet.stat('skill_points')) %> | 
        <b>Equipment Points</b> <%= number_with_delimiter(current_pet.stat('item_points')) %>
      </div>
      <div class="pet_wins_losses">
        <b>Wins</b> <%= number_with_delimiter(current_pet.win) %> | 
        <b>Losses</b> <%= number_with_delimiter(current_pet.loss) %> | 
        <b>Idle Wins</b> <%= number_with_delimiter(current_pet.idle_wins) %> | 
        <b>Idle Losses</b> <%= number_with_delimiter(current_pet.idle_losses) %> | 
        <b>Times Run Away</b> <%= number_with_delimiter(current_pet.runs) %>
      </div>
      </div>
      <hr>
      <center><h3><b>Equipped Items</b></h3></center>
      <div class="pet_equipment">
      <% equipment = ItemsController::EQUIPMENT_SLOTS %>
      <% equipment.keys.each do |i| %>
        <% title = equipment[i].titleize %>
        <% if current_pet.equipment[i] == nil %>
          <div class="pet_equipment_image"><%= image_tag("items/no_item.png", :alt => "Equip an item!", :size => "50x50") %><br />
          <b><%= title %></b><br />
          <%= link_to "Buy some items!", '/shop' %><br />
          </div>
        <% else %>
          <% item = Item.where(:pid => current_pet.equipment[i].to_i).first %>
          <div class="pet_equipment_image"><%= item_image(item, 50) %><br />
          <b><%= title %></b><br />
          Level <%= item.level %><br />
          <%= item.name %><br />
          <% item.description.each do |i| %>
            <%= i %><br />
          <% end %>
          <%= link_to 'Unequip', {:controller => "items", :action => "unequip", :position => i} %>
          </div>
        <% end %>
      <% end %>
      </div>
    </div>
  <% end %>
  
  
  <% if signed_in? && has_pet? && current_pet.in_battle %>
  <% end %>
  
</div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application" %>
</head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= render 'layouts/mid_header' %>
        <% if signed_in? && has_pet? && current_pet.in_battle %>
          <% unless current_page?(:controller => 'pets', :action => 'battle_index') %>
            <div class="flash <%= :error %>"><%= 'You must finish your current battle.' %></div>
          <% end %>
          <%= render 'battles/show' %>
        <% else %>
          <%= yield %>
        <% end %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>